### ISSUE TITLE
[BUG] CLI aasx Generation - use absolute paths and valid relationship IDs

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-sdk#488] opened 2023-12-04 17:43 UTC
Status: The currently generated .aasx  files cannot be imported into the aasx package explorer.

Changes reconsidered after update of AASX Package Explorer

**1) NOT VALID ANY LONGER- Explorer will support relative Paths**
Instead of using relative path use absolute path in aasx-origin.rels and .rels

- in aasx-origin.rels change from   `xml/content.xm`l to `/aasx/xml/content.xml`
- in .rels from `docProps/core.xml` to `/aasx/docProps/core.xml`
- in .rels from `aasx/aasx-origin` to` /aasx/aasx-origin`

**2) Relationship IDs shall not start with a number, no valid ID**

- in .rels and aasx-original.rels add a char as first symbol in ID

example: instead of 
`<Relationship Id="3d013462-90d0-4db7-83b6-22c8276db865" Target="aasx/aasx-origin" Type="http://www.admin-shell.io/aasx/relationships/aasx-origin"/>`
use
`<Relationship Id="A3d013462-90d0-4db7-83b6-22c8276db865" Target="aasx/aasx-origin" Type="http://www.admin-shell.io/aasx/relationships/aasx-origin"/>`

**3) www.admin-shell.io**
in aasx-origin.rels and .rels
 the newest version of the CLI aasx generator writes `http://admin-shell.io/aasx/relationships/aasx-origin` instead of `http://www.admin-shell.io/aasx/relationships/aasx-origin`: add "www" before admin-shell.io 
same for `http://admin-shell.io/aasx/relationships/aas-spec`
**The AAS specification Part 5 requests path without "www"**: https://github.com/admin-shell-io/temp-aasx-package-explorer/issues/124 still needs to be fixed in the aasx package explorer itself. There is an issue for Part 5 to support both path.

**Comment by BirgitBoss** [comment] 2023-12-04 17:48
In #432 only bugs with respect to xml file and import of xml were checked. In this issue aasx package format errors or at least issues hindering the import into the aasx package explorer are identified.

**Comment by BirgitBoss** [comment] 2023-12-04 17:56
compare also to https://github.com/admin-shell-io/aasx-package-explorer/issues/654 discussing the issue with the leading slash

**Comment by FrankSchnicke** [comment] 2023-12-06 15:26
This is not a bug in AAS4J but in the AASX Package Explorer, see https://github.com/admin-shell-io/aasx-package-explorer/issues/654

**Comment by BirgitBoss** [comment] 2023-12-11 07:19
I do not agree, see my comment in https://github.com/admin-shell-io/aasx-package-explorer/issues/654#issuecomment-1839183821:

"In Part 5 Chapter 5.4 File Name Conventions it is stated that /aasx/ shall be the common prefix for all files containing aasx package specific information. So relative paths seem not be conformant to the specification Part 5 V3.0."

**Comment by FrankSchnicke** [comment] 2023-12-11 07:35
Please see my response on https://github.com/admin-shell-io/aasx-package-explorer/issues/654

**Comment by FrankSchnicke** [comment] 2024-02-07 14:19
> 2) Relationship IDs shall not start with a number, no valid ID

This is now fixed in the latest release of AAS4J (aas4j-1.0.0-RC1). (cf. https://github.com/eclipse-aas4j/aas4j/issues/181)

**Comment by atextor** [comment] 2024-02-23 13:50
With the [update to AAS4J 1.0.0](https://github.com/eclipse-esmf/esmf-sdk/pull/530), esmf-sdk and samm-cli incorporate the AAS4J fix (https://github.com/eclipse-aas4j/aas4j/issues/181). Starting with the upcoming [version 2.6.0](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.6.0) of esmf-sdk and samm-cli, generated `.aasx` files will use valid relationship IDs.

The AASX Package Explorer contains a loading [fix](https://github.com/admin-shell-io/aasx-package-explorer/pull/673); in order to load `.aasx` generated by esmf-sdk/samm-cli an AASPE version released after 2024-02-07 is therefore required (at the time of this writing, there is no release yet, but it works with nightly builds such as [this one](https://github.com/admin-shell-io/aasx-package-explorer/actions/runs/7928132196)).

**Closed as completed by atextor** 2024-02-23 13:50 UTC
Labels: bug, acknowledged, aas
