### ISSUE TITLE
BUG:ElementType resolution in AspectModelUrn does not provide the ElementType and isSammUrn is coming as false for SAMM models

### ISSUE THREAD

**Issue by shijinrajbosch** [eclipse-esmf/esmf-sdk#415] opened 2023-08-17 10:24 UTC
**Describe the bug**
ElementType resolution in AspectModelUrndoes not provide the ElementType and isSammUrn is coming as false for SAMM models

We are loading org.apache.jena.rdf.model.Model  by calling ESMF SDK method for the respective "ttl" file.
https://github.com/bci-oss/sldt-semantic-hub/blob/9bb39dbb044943a33379373fd66c6d894730cc8c/backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SdsSdk.java#L52

This we filter the Model on Model nodes and call **AspectModelUrn.fromUrn** method by passing org.apache.jena.rdf.model.**Resource**::**toString** of org.apache.jena.rdf.model.Statement object.

https://github.com/bci-oss/sldt-semantic-hub/blob/9bb39dbb044943a33379373fd66c6d894730cc8c/backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SAMMSdk.java#L120
https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/9bb39dbb044943a33379373fd66c6d894730cc8c/backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SAMMSdk.java#L120

AspectModelUrn.getElementType is not able to identify the correct ElementType.
https://github.com/eclipse-esmf/esmf-sdk/blob/9a764b3d5c52122544447059c7c448b4d656d80e/core/esmf-aspect-model-urn/src/main/java/org/eclipse/esmf/aspectmodel/urn/AspectModelUrn.java#L140

isSammUrn( urn, urnParts, elementType ) method also returning "false" for SAMM models.

https://github.com/eclipse-esmf/esmf-sdk/blob/9a764b3d5c52122544447059c7c448b4d656d80e/core/esmf-aspect-model-urn/src/main/java/org/eclipse/esmf/aspectmodel/urn/AspectModelUrn.java#L141

Hence AspectModelUrn is creating wrongly.

We are not sure whether we have used the SDK in proper way or it is a bug. Do you have a hint to identify the correct usage or bug on this problem ?

**Where**
Method AspectModelUrn.fromUrn

**Comment by atextor** [comment] 2023-09-14 12:04
Hi @shijinrajbosch,
I'm not sure what you expect. I don't see anything that is created wrongly.

An Aspect Model URN's _element type_ is the part of the URN that identifies a certain section of the URN; only the meta model elements and model elements that are part of SAMM (Characteristics, Entitities) have such a section. Regular Aspect Model elements don't have such sections; please compare the [meta model identifiers definition](https://eclipse-esmf.github.io/samm-specification/2.1.0/namespaces.html#meta-model-identifiers-definition) (i.e., how do identifiers _within_ SAMM look like) with the [aspect model identifiers definition](https://eclipse-esmf.github.io/samm-specification/2.1.0/namespaces.html#aspect-model-element-identifiers-definition) (i.e., how to identifiers of model elements defined _by_ SAMM look like). The `isSammUrn()` method determines whether a given URN corresponds to the former (in other words, if it is a _meta model_ element identifier) or if it correponds to the latter (if it is a _model_ element identifier).

We can demonstrate this with the following code:
```java
// URN 1: A regular model element
AspectModelUrn urn1 = AspectModelUrn.fromUrn( "urn:samm:io.catenax.battery.battery_pass:3.0.1#BatteryPass" );
// URN 2: A meta model URN with meta-model element type
AspectModelUrn urn2 = AspectModelUrn.fromUrn( "urn:samm:org.eclipse.esmf.samm:meta-model:2.1.0#Aspect" );
// URN 3: A meta model URN with characteristic element type
AspectModelUrn urn3 = AspectModelUrn.fromUrn( "urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#Text" );

Stream.of( urn1, urn2, urn3 ).forEach(
  urn -> System.out.printf( "URN: %s - elementType: %s - isSammUrn: %s%n",
    urn, urn.getElementType(), urn.isSammUrn() ) );
```

This will print - as expected:

```
URN: urn:samm:io.catenax.battery.battery_pass:3.0.1#BatteryPass - elementType: NONE - isSammUrn: false
URN: urn:samm:org.eclipse.esmf.samm:meta-model:2.1.0#Aspect - elementType: META_MODEL - isSammUrn: true
URN: urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#Text - elementType: CHARACTERISTIC - isSammUrn: true
```

Since IMO this is working as intended, I'll close the issue. Please feel free to re-open it if necessary.

**Closed by atextor** 2023-09-14 12:04 UTC
Labels: bug, acknowledged
