### ISSUE TITLE
[BUG] Incorrect SubmodelElementCollection translation to ValueOnly JSON Schema

### ISSUE THREAD

**Issue by sebbader-sap** [eclipse-esmf/esmf-sdk#320] opened 2023-03-09 15:04 UTC
**Describe the bug**
A SubmodelTemplate containing a SubmodelElementCollection is represented as a JSON Objet in the ValueOnly serialisation. For SerialPartTypization for instance, the SubmodelElementCollection with the idShort `localIdentifiers` contains the SubmodelElementCollection `KeyValueList` which should lead to an instance like e.g.:

```
{
    "localIdentifiers": {   # <- idShort of first SMC
        "KeyValueList":    # <- idShort of second SMC 
        {
            "key": "PartInstanceID",
            "value": "XY-ABC1-1234567890"
        }
    },
    "manufacturingInformation": {
        "date": "2022-02-12T01:35:46.089Z",
        "country": "DEU"
    },
    "catenaXId": "12345678-1234-1234-1234-123456789abc",
    "partTypeInformation": {
        "manufacturerPartId": "ABC1",
        "customerPartId": "ABC1",
        "classification": "product",
        "nameAtManufacturer": "ABC 1",
        "nameAtCustomer": "ABC 2"
    }
}
```

However, the JSON Schema for SerialPartTypization in the SemanticHub states that it's not valid but should look like the following:
```
{
    "localIdentifiers": [    # <-- note the JSON Array here
        {
            "key": "PartInstanceID",
            "value": "XY-ABC1-1234567890"
        }
    ],
    "manufacturingInformation": {
        "date": "2022-02-12T01:35:46.089Z",
        "country": "DEU"
    },
    "catenaXId": "12345678-1234-1234-1234-123456789abc",
    "partTypeInformation": {
        "manufacturerPartId": "ABC1",
        "customerPartId": "ABC1",
        "classification": "product",
        "nameAtManufacturer": "ABC 1",
        "nameAtCustomer": "ABC 2"
    }
}
```

**Where**
sds-aspect-model-aas-generator?

**Screenshots**
see example above.

**Additional context**
If an array in the ValueOnly representation is desired, the SubmodelTemplate should have a SubmodelElementList for the `localIdentifiers`. Nevertheless, I think the translation of a SubmodelElementCollection to a JSON Array is not correct.

**Comment by BirgitBoss** [comment] 2023-03-12 18:14
Exactly: local identifiers would not be mapped to a submodel element collection but to a submodel element list in V3.0. For submodel element list a JSON array should be correct, why do you think it still would not be correct?

**Comment by sebbader-sap** [comment] 2023-03-13 15:25
I don't understand the relation to V3.0, unfortunately. The SubmodelTemplate `SerialPartTypization` states that the SubmodelElement with the idShort `localIdentifiers` is a `SubmodelElementCollection`. Independent whether or not it _should_ be a `SubmodelElementCollection` or a `SubmodelElementList`, the translation receives a `SubmodelElementCollection` as the input but outputs a `JSON Array`. This is - as I think at the moment - not the intended behaviour.

**Comment by atextor** [comment] 2023-05-16 11:10
Hi @sebbader-sap,
I think you are talking about the [SerialPartTypization](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.serial_part_typization/1.1.1/SerialPartTypization.ttl) Aspect Model that is part of Tractus X, which is not related to the ESMF project, but uses SAMM as to express Aspect Models.

This model states the following (simplified):
```turtle
:localIdentifiers a bamm:Property ;
  bamm:characteristic :LocalIdentifierCharacteristic .

:LocalIdentifierCharacteristic a bamm-c:Set ;
  bamm:dataType :KeyValueList .

:KeyValueList a bamm:Entity ;
  bamm:properties ( :key :value ) .
```

So it defines values of the property `localIdentifiers` to be a collection of entities, each of which have a key and a value. All SAMM collection types, i.e., [Collection](https://eclipse-esmf.github.io/samm-specification/2.0.0/characteristics.html#collection-characteristic), [List](https://eclipse-esmf.github.io/samm-specification/2.0.0/characteristics.html#list-characteristic), [Set](https://eclipse-esmf.github.io/samm-specification/2.0.0/characteristics.html#set-characteristic) and [SortedSet](https://eclipse-esmf.github.io/samm-specification/2.0.0/characteristics.html#sorted-set-characteristic), are [mapped to JSON arrays](https://eclipse-esmf.github.io/samm-specification/2.0.0/payloads.html) in payloads, so the translation is correct and to be expected. Collections in SAMM/ESMF context are comparable to collection types in most programming languages, i.e., they contain multiple elements of the same type.

For a potential closer alignment of AAS terminology with SAMM terminology, this discussion should take place in the context of the [Semantic Aspect Meta Model](https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model) itself. For getting JSON payloads out of the TractusX models that align with the expected AAS ValueOnly serialization, the models in the [TractusX SLDT models](https://github.com/eclipse-tractusx/sldt-semantic-models) project should be adjusted accordingly (e.g., by using Entities instead of Collections, which will map to regular JSON objects).

Since IMO this is not a bug in the esmf-sdk, I'll close this issue. Please feel free to reopen if necessary.

**Closed by atextor** 2023-05-16 11:10 UTC
Labels: bug, acknowledged
