### ISSUE TITLE
[BUG] Font.createFont() method doesn't delete tmp file +~JF<<random_number>>.tmp after request completes.

### ISSUE THREAD

**Issue by richaashara** [eclipse-esmf/esmf-sdk#371] opened 2023-06-21 05:54 UTC
**generatePng()** method inside **AspectModelDiagramGenerator class** invokes, **Font.createFont()** method. which creates a tmp font file with name pattern  +~JF<<random_number>>.tmp but doesn't delete it after the request is completed.

I am using JDK 17.
I am using this SDK in a Java application and running through a docker container. So, the docker container memory is keeping increasing sequentially after each request. As these files are going to be stored inside the container's tmp.

If I run java application without container than, those files are deleting on stopping the application. 

Code snippet where this is happemning:
```java
private void generatePng(String dotInput, OutputStream output) throws IOException {
        try {
            InputStream fontStream = this.getInputStream("diagram/RobotoCondensed-Regular.ttf");

            try {
                Font f = Font.createFont(0, fontStream);
                GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                ge.registerFont(f);
            } catch (Throwable var7) {
                if (fontStream != null) {
                    try {
                        fontStream.close();
                    } catch (Throwable var6) {
                        var7.addSuppressed(var6);
                    }
                }

                throw var7;
            }

            if (fontStream != null) {
                fontStream.close();
            }
        } catch (FontFormatException var8) {
        }

        MutableGraph g = (new Parser()).read(dotInput);
        Graphviz graphviz = Graphviz.fromGraph(g);
        graphviz.render(guru.nidi.graphviz.engine.Format.PNG).toOutputStream(output);
    }
```

Font method decompiled implementation is as below . :
```java
private static Font[] createFont0(int fontFormat, InputStream fontStream, boolean allFonts, CreatedFontTracker tracker) throws FontFormatException, IOException {
        if (fontFormat != 0 && fontFormat != 1) {
            throw new IllegalArgumentException("font format not recognized");
        } else {
            boolean copiedFontData = false;

            try {
                final File tFile = (File)AccessController.doPrivileged(new PrivilegedExceptionAction<File>() {
                    public File run() throws IOException {
                        return Files.createTempFile("+~JF", ".tmp").toFile();
                    }
                });
                if (tracker != null) {
                    tracker.add(tFile);
                }

                int totalSize = 0;

                try {
                    OutputStream outStream = (OutputStream)AccessController.doPrivileged(new PrivilegedExceptionAction<OutputStream>() {
                        public OutputStream run() throws IOException {
                            return new FileOutputStream(tFile);
                        }
                    });
                    if (tracker != null) {
                        tracker.set(tFile, outStream);
                    }

                    try {
                        byte[] buf = new byte[8192];

                        while(true) {
                            int bytesRead = fontStream.read(buf);
                            if (bytesRead < 0) {
                                break;
                            }

                            if (tracker != null) {
                                if (totalSize + bytesRead > 33554432) {
                                    throw new IOException("File too big.");
                                }

                                if (totalSize + tracker.getNumBytes() > 335544320) {
                                    throw new IOException("Total files too big.");
                                }

                                totalSize += bytesRead;
                                tracker.addBytes(bytesRead);
                            }

                            outStream.write(buf, 0, bytesRead);
                        }
                    } finally {
                        outStream.close();
                    }

                    copiedFontData = true;
                    FontManager var24 = FontManagerFactory.getInstance();
                    Font2D[] font2DArr = var24.createFont2D(tFile, fontFormat, allFonts, true, tracker);
                    int num = font2DArr.length;
                    Font[] fonts = new Font[num];

                    for(int i = 0; i < num; ++i) {
                        fonts[i] = new Font(font2DArr[i]);
                    }

                    Font[] var26 = fonts;
                    return var26;
                } finally {
                    if (tracker != null) {
                        tracker.remove(tFile);
                    }

                    if (!copiedFontData) {
                        if (tracker != null) {
                            tracker.subBytes(totalSize);
                        }

                        class NamelessClass_1 implements PrivilegedExceptionAction<Void> {
                            NamelessClass_1() {
                            }

                            public Void run() {
                                tFile.delete();
                                return null;
                            }
                        }

                        AccessController.doPrivileged(new NamelessClass_1());
                    }

                }
            } catch (Throwable var22) {
                if (var22 instanceof FontFormatException) {
                    throw (FontFormatException)var22;
                } else if (var22 instanceof IOException) {
                    throw (IOException)var22;
                } else {
                    Throwable cause = var22.getCause();
                    if (cause instanceof FontFormatException) {
                        throw (FontFormatException)cause;
                    } else {
                        throw new IOException("Problem reading font data.");
                    }
                }
            }
        }
    }
```
In case of success, flag copiedFontData is going to be always true. so, finalluy block will not delete the tmp file.

**Solution:**

We Get the font file name  or all files with name pattern in tmp and delete the file in finally block of generatePng() method

Edit by @atextor: Fixed formatting markup

**Comment by atextor** [comment] 2023-06-21 09:40
Hi @richaashara ,
if I understand correctly, the bug you are reporting is: Calling Aspect Model diagram generation leaves temp files in the system. As you correctly determined, this is caused by code in `java.awt.Font`, which is part of the Java JDK. If I understand the JDK code correctly, the deleting of the temp file in the `finally` block is only meant for the case when the font file is invalid, so it can be directly deleted. In case of success, the temp file is supposed to stay around after creation, because the font manager might look inside the font file at a later point to load glyphs. Only when the temp file is not needed any more, it will be deleted by the Java runtime. You can see [here](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/java/awt/Font.java#L1081) that JDK uses a so-called `CreatedFontTracker` for that.

However, in the JDK issue tracker, there exists [an issue](https://bugs.openjdk.org/browse/JDK-8239833) for not releasing font temp files, which is marked as fixed. Comments there indicate that temp files are deleted eventually by the Java runtime. I don't know the exact mechanics about when and how those file are deleted, but if this does indeed not happen, you might want to open a new issue there, since there is not much we can do about this in the esmf-sdk.

Therefore, I'll close the issue; please feel free to still comment on and, if necessary, reopen the issue.

PS: FYI, there is no need to copy and paste decompiled JDK code, we can just link to [the original source code of `createFont0`](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/java/awt/Font.java#L1099-L1207).

**Comment by atextor** [comment] 2023-06-28 11:34
Update: A [JDK issue](https://bugs.openjdk.org/browse/JDK-8310725) was created, but was closed ("not an issue") even though the cause seems to be a different one; the current cause seems to be temp files that are written to but not closed. Even if this were addressed in the JDK, it would take a while, which is why we can implement the following workaround:

By using [`createFont(int fontFormat, File fontFile)`](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/java/awt/Font.java#L1243) instead, we can create a temp file (using `java.nio.file.Files#createTempFile`), write the content of the font resource to the file and create the font from this; then deleting the temp file explicitly after diagram generation. This will incur a minor perfomance overhead but will make sure no temporary files keep lingering around.

**Closed** 2023-07-12 07:17 UTC
Labels: bug, acknowledged
